// Generated by ReScript, PLEASE EDIT WITH CARE

import Dataloader from "dataloader";
import * as Stdlib_Lazy from "@rescript/runtime/lib/es6/Stdlib_Lazy.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as StableStringifyMjs from "./stableStringify.mjs";

let Plain = {};

function stableStringifyValue(prim) {
  return StableStringifyMjs.stableStringify(prim);
}

function mapOptions(options) {
  let baseOpts_cacheKeyFn = stableStringifyValue;
  let baseOpts = {
    cacheKeyFn: baseOpts_cacheKeyFn
  };
  if (options === undefined) {
    return baseOpts;
  }
  let newrecord = {...baseOpts};
  return newrecord.name = options.name, newrecord.batchScheduleFn = options.batchScheduleFn, newrecord;
}

function makeSingle(loadFn, options) {
  return Stdlib_Lazy.make(() => new Dataloader(keys => Promise.all(keys.map(loadFn)), Primitive_option.toUndefined(mapOptions(options))));
}

function makeBatched(loadFn, options) {
  return Stdlib_Lazy.make(() => new Dataloader(loadFn, Primitive_option.toUndefined(mapOptions(options))));
}

function load(lazyLoader, key) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.load(key);
}

function loadMany(lazyLoader, keys) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.loadMany(keys);
}

function clear(lazyLoader, key) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.clear(key);
}

function clearAll(lazyLoader) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.clearAll();
}

function prime(lazyLoader, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(value);
}

function primeWithPromise(lazyLoader, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(value);
}

function name(lazyLoader) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return Primitive_option.fromNullable(loader.name);
}

export {
  Plain,
  makeSingle,
  makeBatched,
  load,
  loadMany,
  clear,
  clearAll,
  prime,
  primeWithPromise,
  name,
}
/* dataloader Not a pure module */
