// Generated by ReScript, PLEASE EDIT WITH CARE

import Dataloader from "dataloader";
import * as Stdlib_Lazy from "@rescript/runtime/lib/es6/Stdlib_Lazy.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as StableStringifyMjs from "./stableStringify.mjs";

let Plain = {};

function stableStringifyValue(prim) {
  return StableStringifyMjs.stableStringify(prim);
}

function mapOptions(options) {
  let baseOpts_cacheKeyFn = stableStringifyValue;
  let baseOpts = {
    cacheKeyFn: baseOpts_cacheKeyFn
  };
  if (options === undefined) {
    return baseOpts;
  }
  let newrecord = {...baseOpts};
  return newrecord.name = options.name, newrecord.batchScheduleFn = options.batchScheduleFn, newrecord;
}

function makeSingle(loadFn, options) {
  return Stdlib_Lazy.make(() => new Dataloader(keys => Promise.all(keys.map(loadFn)), Primitive_option.toUndefined(mapOptions(options))));
}

function makeBatched(loadFn, options) {
  return Stdlib_Lazy.make(() => new Dataloader(loadFn, Primitive_option.toUndefined(mapOptions(options))));
}

let errorToRawLoadManyEntry = (error => {
  if (error instanceof Error) return error;
  const message = error != null && typeof error.RE_EXN_ID === "string"
    ? error.RE_EXN_ID
    : String(error);
  const wrapped = new Error(message);
  Object.defineProperty(wrapped, "__resgraphException", {value: error});
  return wrapped;
});

function makeBatchedResults(loadFn, options) {
  let rawLoadFn = keys => loadFn(keys).then(results => results.map(result => {
    if (result.TAG === "Ok") {
      return result._0;
    } else {
      return errorToRawLoadManyEntry(result._0);
    }
  }));
  return Stdlib_Lazy.make(() => new Dataloader(rawLoadFn, Primitive_option.toUndefined(mapOptions(options))));
}

function load(lazyLoader, key) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.load(key);
}

function loadMany(lazyLoader, keys) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.loadMany(keys);
}

let isError = (value => value instanceof Error);

let rawLoadManyEntryToError = (value =>
  Object.prototype.hasOwnProperty.call(value, "__resgraphException")
    ? value.__resgraphException
    : value);

function loadManyResults(lazyLoader, keys) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.loadMany(keys).then(values => values.map(value => {
    if (isError(value)) {
      return {
        TAG: "Error",
        _0: rawLoadManyEntryToError(value)
      };
    } else {
      return {
        TAG: "Ok",
        _0: value
      };
    }
  }));
}

function clear(lazyLoader, key) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.clear(key);
}

function clearAll(lazyLoader) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.clearAll();
}

function prime(lazyLoader, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(value);
}

function primeAt(lazyLoader, key, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(key, value);
}

function primeWithPromise(lazyLoader, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(value);
}

function primeWithPromiseAt(lazyLoader, key, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(key, value);
}

function name(lazyLoader) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return Primitive_option.fromNullable(loader.name);
}

export {
  Plain,
  makeSingle,
  makeBatched,
  makeBatchedResults,
  load,
  loadMany,
  loadManyResults,
  clear,
  clearAll,
  prime,
  primeAt,
  primeWithPromise,
  primeWithPromiseAt,
  name,
}
/* dataloader Not a pure module */
