// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib_Lazy = require("@rescript/runtime/lib/js/Stdlib_Lazy.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let StableStringifyCjs = require("./stableStringify.cjs");
let DataLoaderCompatCjs = require("./dataLoaderCompat.cjs");

function make(prim0, prim1) {
  return new DataLoaderCompatCjs.DataLoader(prim0, prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
}

let Plain = {
  make: make
};

function stableStringifyValue(prim) {
  return StableStringifyCjs.stableStringify(prim);
}

function mapOptions(options) {
  let baseOpts_cacheKeyFn = stableStringifyValue;
  let baseOpts = {
    cacheKeyFn: baseOpts_cacheKeyFn
  };
  if (options === undefined) {
    return baseOpts;
  }
  let newrecord = {...baseOpts};
  return newrecord.name = options.name, newrecord.batchScheduleFn = options.batchScheduleFn, newrecord;
}

function makeSingle(loadFn, options) {
  return Stdlib_Lazy.make(() => new DataLoaderCompatCjs.DataLoader(keys => Promise.all(keys.map(loadFn)), Primitive_option.toUndefined(mapOptions(options))));
}

function makeBatched(loadFn, options) {
  return Stdlib_Lazy.make(() => new DataLoaderCompatCjs.DataLoader(loadFn, Primitive_option.toUndefined(mapOptions(options))));
}

function load(lazyLoader, key) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.load(key);
}

function loadMany(lazyLoader, keys) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return loader.loadMany(keys);
}

function clear(lazyLoader, key) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.clear(key);
}

function clearAll(lazyLoader) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.clearAll();
}

function prime(lazyLoader, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(value);
}

function primeWithPromise(lazyLoader, value) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  loader.prime(value);
}

function name(lazyLoader) {
  let loader = Stdlib_Lazy.get(lazyLoader);
  return Primitive_option.fromNullable(loader.name);
}

exports.Plain = Plain;
exports.makeSingle = makeSingle;
exports.makeBatched = makeBatched;
exports.load = load;
exports.loadMany = loadMany;
exports.clear = clear;
exports.clearAll = clearAll;
exports.prime = prime;
exports.primeWithPromise = primeWithPromise;
exports.name = name;
/* ./stableStringify.cjs Not a pure module */
