// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function raise(err) {
  throw err;
}

let GraphQLError = {
  raise: raise
};

let Rule = {};

let ExtendedValidation = {
  Rule: Rule
};

let Plugin = {
  ExtendedValidation: ExtendedValidation
};

let Envelope = {
  Plugin: Plugin
};

let Server = {};

let NodeHttpServer = {};

let Request;

let Headers;

let Body;

let FormData;

let Blob;

exports.Request = Request;
exports.Headers = Headers;
exports.Body = Body;
exports.FormData = FormData;
exports.Blob = Blob;
exports.GraphQLError = GraphQLError;
exports.Envelope = Envelope;
exports.Server = Server;
exports.NodeHttpServer = NodeHttpServer;
/* No side effect */
