// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphqlRelayConnectionsCjs from "./graphqlRelayConnections.cjs";

function encode(prim) {
  return GraphqlRelayConnectionsCjs.encodeBase64(prim);
}

function decode(prim) {
  return GraphqlRelayConnectionsCjs.decodeBase64(prim);
}

let Base64 = {
  encode: encode,
  decode: decode
};

export {
  Base64,
}
/* ./graphqlRelayConnections.cjs Not a pure module */
