// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphqlRelayConnectionsMjs from "./graphqlRelayConnections.mjs";

function connectionFromArray(prim0, prim1) {
  return GraphqlRelayConnectionsMjs.connectionFromArray(prim0, prim1);
}

export {
  connectionFromArray ,
}
/* ./graphqlRelayConnections.mjs Not a pure module */
