// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Graphql from "graphql";
import * as Nodecrypto from "node:crypto";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function hashQuery(query) {
  return Nodecrypto.createHash("sha256").update(query).digest("hex");
}

function makeQueryDocumentCache() {
  return {};
}

function setCachedQuery(cache, query, document) {
  cache[hashQuery(query)] = document;
}

function getCachedQuery(cache, query) {
  return cache[hashQuery(query)];
}

function parseQueryCached(cache, query) {
  let document = cache[hashQuery(query)];
  if (document !== undefined) {
    return Primitive_option.valFromOption(document);
  }
  let document$1 = Graphql.parse(query);
  cache[hashQuery(query)] = document$1;
  return document$1;
}

function executeParsed(schema, document, contextValue, variableValues, operationName, rootValue) {
  return Graphql.execute({
    schema: schema,
    document: document,
    contextValue: contextValue,
    variableValues: variableValues,
    operationName: operationName,
    rootValue: rootValue
  });
}

function execute(schema, query, contextValue, cache, variableValues, operationName, rootValue) {
  let document = cache !== undefined ? parseQueryCached(cache, query) : Graphql.parse(query);
  return executeParsed(schema, document, contextValue, variableValues, operationName, rootValue);
}

function Execute_parseQuery(prim) {
  return Graphql.parse(prim);
}

let Execute = {
  parseQuery: Execute_parseQuery,
  makeQueryDocumentCache: makeQueryDocumentCache,
  setCachedQuery: setCachedQuery,
  getCachedQuery: getCachedQuery,
  parseQueryCached: parseQueryCached,
  executeParsed: executeParsed,
  execute: execute
};

let ResolveInfo = {};

let GraphQLLiteralValue;

let $$JSON;

let Connections;

let Utils;

export {
  GraphQLLiteralValue,
  $$JSON,
  Connections,
  Utils,
  Execute,
  ResolveInfo,
}
/* graphql Not a pure module */
