// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let GraphqlRelayConnectionsMjs = require("./graphqlRelayConnections.mjs");

function connectionFromArray(prim0, prim1) {
  return GraphqlRelayConnectionsMjs.connectionFromArray(prim0, prim1);
}

exports.connectionFromArray = connectionFromArray;
/* ./graphqlRelayConnections.mjs Not a pure module */
