// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphqlRelayConnectionsCjs from "./graphqlRelayConnections.cjs";

function connectionFromArray(prim0, prim1) {
  return GraphqlRelayConnectionsCjs.connectionFromArray(prim0, prim1);
}

export {
  connectionFromArray,
}
/* ./graphqlRelayConnections.cjs Not a pure module */
