// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let GraphqlRelayConnectionsCjs = require("./graphqlRelayConnections.cjs");

function connectionFromArray(prim0, prim1) {
  return GraphqlRelayConnectionsCjs.connectionFromArray(prim0, prim1);
}

exports.connectionFromArray = connectionFromArray;
/* ./graphqlRelayConnections.cjs Not a pure module */
