// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let GraphqlRelayConnectionsMjs = require("./graphqlRelayConnections.mjs");

function encode(prim) {
  return GraphqlRelayConnectionsMjs.encodeBase64(prim);
}

function decode(prim) {
  return GraphqlRelayConnectionsMjs.decodeBase64(prim);
}

let Base64 = {
  encode: encode,
  decode: decode
};

exports.Base64 = Base64;
/* ./graphqlRelayConnections.mjs Not a pure module */
