// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let GraphqlRelayConnectionsCjs = require("./graphqlRelayConnections.cjs");

function encode(prim) {
  return GraphqlRelayConnectionsCjs.encodeBase64(prim);
}

function decode(prim) {
  return GraphqlRelayConnectionsCjs.decodeBase64(prim);
}

let Base64 = {
  encode: encode,
  decode: decode
};

exports.Base64 = Base64;
/* ./graphqlRelayConnections.cjs Not a pure module */
