#!/usr/bin/env node
// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Lsp = require("./Lsp.js");
let Utils = require("./Utils.js");
let Stdlib = require("@rescript/runtime/lib/js/Stdlib.js");
let Process = require("process");
let Stdlib_Exn = require("@rescript/runtime/lib/js/Stdlib_Exn.js");
let InitProject = require("./InitProject.js");
let Stdlib_List = require("@rescript/runtime/lib/js/Stdlib_List.js");
let ErrorPrinter = require("./ErrorPrinter.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Nodeperf_hooks = require("node:perf_hooks");
let GeneratedArtifacts = require("./GeneratedArtifacts.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let args = Stdlib_Array.keepSome(process.argv.slice(2));

let argsList = Stdlib_List.fromArray(args);

function printBuildTime(schema, buildDuration, showSchemaName) {
  let prefix = showSchemaName ? `[` + schema.name + `] ` : "";
  console.log(prefix + `Build succeeded in ` + (buildDuration / 1000).toFixed(2) + ` seconds.`);
}

function printAuthorizationBaselineWarning(authorization) {
  let baselinePath = Stdlib_Option.flatMap(authorization, authorization => authorization.baselinePath);
  if (baselinePath !== undefined) {
    console.warn(`⚠️ Authorization baseline active: fields listed in ` + baselinePath + ` are not protected by required authorization coverage.`);
    return;
  }
}

let helpText = `
**ResGraph v0.1.0 CLI**
This is the CLI of ResGraph. All configuration is read from \`resgraph.json\`.
Available commands:

init                            | Validate the project configuration.
build [schema]                  | Build all schemas, or one named schema.
authorization baseline [schema] | Create or update a schema's authorization baseline.
watch [schema]                  | Watch all schemas, or one named schema.
tools                           | Show available ResGraph tools.
help                            | Show this help message.
`;

let toolsHelpText = `
Tools commands:

find-definition <TypeName[.fieldName]> [--schema <schema>] [--json]
`;

function parseFindDefinitionArgs(args) {
  let _remaining = args;
  let _state = {
    target: undefined,
    jsonOutput: false,
    schemaName: undefined
  };
  while (true) {
    let state = _state;
    let remaining = _remaining;
    if (remaining === 0) {
      return Stdlib_Option.map(state.target, target => ({
        target: target,
        jsonOutput: state.jsonOutput,
        schemaName: state.schemaName
      }));
    }
    let target = remaining.hd;
    switch (target) {
      case "--json" :
        if (!state.jsonOutput) {
          _state = {
            target: state.target,
            jsonOutput: true,
            schemaName: state.schemaName
          };
          _remaining = remaining.tl;
          continue;
        }
        break;
      case "--schema" :
        let match = remaining.tl;
        if (match !== 0 && Stdlib_Option.isNone(state.schemaName)) {
          _state = {
            target: state.target,
            jsonOutput: state.jsonOutput,
            schemaName: match.hd
          };
          _remaining = match.tl;
          continue;
        }
        break;
    }
    if (!(Stdlib_Option.isNone(state.target) && !target.startsWith("--"))) {
      return;
    }
    _state = {
      target: target,
      jsonOutput: state.jsonOutput,
      schemaName: state.schemaName
    };
    _remaining = remaining.tl;
    continue;
  };
}

function readConfig() {
  let msg = Utils.readConfigFromCwd();
  if (msg.TAG === "Ok") {
    return msg._0;
  } else {
    return Stdlib.panic(msg._0);
  }
}

function validateConfig(config) {
  let issues = [];
  InitProject.validateConfig(config, issues, Process.cwd());
  if (issues.length !== 0) {
    InitProject.printProjectIssues(issues);
    Process.exit(1);
    return;
  }
}

function selectSchemas(config, schemaName) {
  if (schemaName === undefined) {
    return config.schemas;
  }
  let schema = Utils.findSchema(config, schemaName);
  if (schema !== undefined) {
    return [schema];
  } else {
    console.error(`Unknown ResGraph schema "` + schemaName + `".`);
    Process.exit(1);
    return [];
  }
}

function printFindDefinition(target, jsonOutput, schemaName) {
  let config = readConfig();
  validateConfig(config);
  let schema = schemaName !== undefined ? Utils.findSchema(config, schemaName) : Utils.defaultSchema(config);
  if (schema !== undefined) {
    let stateName = schema.stateName;
    let match = Utils.callPrivateCli({
      TAG: "FindDefinition",
      filePath: schema.projectRoot,
      definitionHint: target,
      stateName: stateName
    });
    if (typeof match === "object" && match.status === "FindDefinition") {
      let item = match.item;
      if (item !== undefined) {
        if (match.error === undefined) {
          if (jsonOutput) {
            console.log(Utils.stringifyFindDefinitionJson(item));
          } else {
            console.log(Utils.formatFindDefinitionText(item));
          }
          return;
        }
      } else {
        let error = match.error;
        if (error !== undefined) {
          if (jsonOutput) {
            console.log(Utils.stringifyFindDefinitionError(error));
          } else {
            console.error(error);
          }
          Process.exit(1);
          return;
        }
      }
    }
    console.error("Unexpected response from ResGraph tools command.");
    Process.exit(1);
    return;
  }
  console.error("Could not select a ResGraph schema.");
  Process.exit(1);
}

function buildSchemas(config, schemas) {
  let showSchemaName = !config.legacy || schemas.length > 1;
  let hadError = {
    contents: false
  };
  schemas.forEach(schema => {
    let timeStart = Nodeperf_hooks.performance.now();
    try {
      let match = Utils.callPrivateCli({
        TAG: "GenerateSchema",
        _0: schema
      });
      if (typeof match !== "object") {
        return;
      }
      switch (match.status) {
        case "Success" :
          printBuildTime(schema, Nodeperf_hooks.performance.now() - timeStart, showSchemaName);
          return printAuthorizationBaselineWarning(schema.authorization);
        case "Error" :
          if (showSchemaName) {
            console.error(`[` + schema.name + `] Schema generation failed.`);
          }
          ErrorPrinter.printErrors(match.errors);
          hadError.contents = true;
          return;
        default:
          return;
      }
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error(`[` + schema.name + `] Generator process failed.`);
        console.error(error._1);
        hadError.contents = true;
      } else {
        console.error(`[` + schema.name + `] Generator process failed.`);
        hadError.contents = true;
      }
      return;
    }
  });
  if (hadError.contents) {
    Process.exit(1);
    return;
  }
}

function generateAuthorizationBaseline(schemaName) {
  let config = readConfig();
  validateConfig(config);
  let schema = schemaName !== undefined ? Utils.findSchema(config, schemaName) : Utils.defaultSchema(config);
  let schema$1 = Stdlib_Option.getOrThrow(schema, "Could not select a ResGraph schema.");
  let authorization = schema$1.authorization;
  if (authorization !== undefined) {
    let baselinePath = authorization.baselinePath;
    if (baselinePath !== undefined) {
      let newrecord = {...authorization};
      newrecord.mode = "Baseline";
      let newrecord$1 = {...schema$1};
      newrecord$1.authorization = newrecord;
      GeneratedArtifacts.sync(config, [newrecord$1], Process.cwd());
      let match = Utils.callPrivateCli({
        TAG: "GenerateSchema",
        _0: newrecord$1
      });
      if (typeof match === "object") {
        switch (match.status) {
          case "Success" :
            console.log(`Authorization baseline written to ` + baselinePath + `.`);
            return printAuthorizationBaselineWarning(newrecord);
          case "Error" :
            ErrorPrinter.printErrors(match.errors);
            Process.exit(1);
            return;
        }
      }
      console.error("Unexpected response while creating the authorization baseline.");
      Process.exit(1);
      return;
    }
    console.error("Set `authorization.baselinePath` in resgraph.json before creating a baseline.");
    Process.exit(1);
    return;
  }
  console.error(`Required authorization must be configured for schema "` + schema$1.name + `" before creating a baseline.`);
  Process.exit(1);
}

try {
  let exit = 0;
  if (argsList !== 0) {
    switch (argsList.hd) {
      case "authorization" :
        let match = argsList.tl;
        if (match !== 0 && match.hd === "baseline") {
          let match$1 = match.tl;
          if (match$1 !== 0) {
            if (match$1.tl !== 0) {
              exit = 1;
            } else {
              generateAuthorizationBaseline(match$1.hd);
            }
          } else {
            generateAuthorizationBaseline(undefined);
          }
        } else {
          exit = 1;
        }
        break;
      case "build" :
        let match$2 = argsList.tl;
        if (match$2 !== 0) {
          if (match$2.tl !== 0) {
            exit = 1;
          } else {
            let config = readConfig();
            validateConfig(config);
            let schemas = selectSchemas(config, match$2.hd);
            GeneratedArtifacts.sync(config, schemas, Process.cwd());
            buildSchemas(config, schemas);
          }
        } else {
          let config$1 = readConfig();
          validateConfig(config$1);
          let schemas$1 = selectSchemas(config$1, undefined);
          GeneratedArtifacts.sync(config$1, schemas$1, Process.cwd());
          buildSchemas(config$1, schemas$1);
        }
        break;
      case "help" :
        if (argsList.tl !== 0) {
          exit = 1;
        } else {
          console.log(helpText);
        }
        break;
      case "init" :
        if (argsList.tl !== 0) {
          exit = 1;
        } else {
          let issues = InitProject.validateProject(Process.cwd());
          if (issues.length !== 0) {
            InitProject.printProjectIssues(issues);
            Process.exit(1);
          } else {
            console.log("✅ Project already set up correctly.");
          }
        }
        break;
      case "lsp" :
        let match$3 = argsList.tl;
        if (match$3 !== 0 && match$3.tl === 0) {
          Lsp.start("Stdio", match$3.hd);
        } else {
          exit = 1;
        }
        break;
      case "tools" :
        let match$4 = argsList.tl;
        if (match$4 !== 0 && match$4.hd === "find-definition") {
          let match$5 = parseFindDefinitionArgs(match$4.tl);
          if (match$5 !== undefined) {
            printFindDefinition(match$5.target, match$5.jsonOutput, match$5.schemaName);
          } else {
            console.error("Invalid tools arguments.");
            console.log(toolsHelpText);
            Process.exit(1);
          }
        } else {
          exit = 1;
        }
        break;
      case "watch" :
        let match$6 = argsList.tl;
        exit = match$6 !== 0 && match$6.tl !== 0 ? 1 : 2;
        break;
      default:
        exit = 1;
    }
  } else {
    exit = 1;
  }
  switch (exit) {
    case 1 :
      console.log("Invalid command: " + Stdlib_List.toArray(argsList).join(" "));
      console.log(helpText);
      break;
    case 2 :
      let config$2 = readConfig();
      validateConfig(config$2);
      let schemaName;
      if (argsList !== 0 && argsList.hd === "watch") {
        let match$7 = argsList.tl;
        schemaName = match$7 !== 0 && match$7.tl === 0 ? match$7.hd : undefined;
      } else {
        schemaName = undefined;
      }
      let schemas$2 = selectSchemas(config$2, schemaName);
      GeneratedArtifacts.sync(config$2, schemas$2, Process.cwd());
      let showSchemaName = !config$2.legacy || schemas$2.length > 1;
      let timeStarts = {};
      schemas$2.map(schema => Utils.setupWatcher((schema, res) => {
        let timeStart = timeStarts[schema.name];
        if (timeStart === undefined) {
          return;
        }
        if (typeof res !== "object") {
          return;
        }
        let match = res._0;
        if (typeof match === "object") {
          switch (match.status) {
            case "Success" :
              printBuildTime(schema, Nodeperf_hooks.performance.now() - timeStart, showSchemaName);
              return printAuthorizationBaselineWarning(schema.authorization);
            case "Error" :
              if (showSchemaName) {
                console.error(`[` + schema.name + `] Schema generation failed.`);
              }
              return ErrorPrinter.printErrors(match.errors);
          }
        }
        console.error(`[` + schema.name + `] Unexpected generator response.`);
      }, schema => {
        timeStarts[schema.name] = Nodeperf_hooks.performance.now();
        if (showSchemaName) {
          console.log(`[` + schema.name + `] Rebuilding.`);
        } else {
          console.log("Rebuilding.");
        }
      }, schema));
      console.log("Watching for changes...");
      break;
  }
} catch (raw_error) {
  let error = Primitive_exceptions.internalToException(raw_error);
  if (error.RE_EXN_ID === Stdlib_Exn.$$Error) {
    console.error(error._1);
    Process.exit(1);
  } else {
    console.error("Error!");
    Process.exit(1);
  }
}

let Console;

let JsExn;

exports.Console = Console;
exports.JsExn = JsExn;
exports.args = args;
exports.argsList = argsList;
exports.printBuildTime = printBuildTime;
exports.printAuthorizationBaselineWarning = printAuthorizationBaselineWarning;
exports.helpText = helpText;
exports.toolsHelpText = toolsHelpText;
exports.parseFindDefinitionArgs = parseFindDefinitionArgs;
exports.readConfig = readConfig;
exports.validateConfig = validateConfig;
exports.selectSchemas = selectSchemas;
exports.printFindDefinition = printFindDefinition;
exports.buildSchemas = buildSchemas;
exports.generateAuthorizationBaseline = generateAuthorizationBaseline;
/* args Not a pure module */
