// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Chalk = require("chalk").default;
let Nodefs = require("node:fs");
let Nodeos = require("node:os");

let Chalk$1 = {};

function prettyPrintDiagnostic(lines, diagnostic) {
  let fileLocText = Chalk.blackBright((diagnostic.range.start.line + 1 | 0).toString() + `:` + (diagnostic.range.start.character + 1 | 0).toString() + `-` + (diagnostic.range.end.line + 1 | 0).toString() + `:` + (diagnostic.range.end.character + 1 | 0).toString());
  console.log(Chalk.red("Error in file:") + ` ` + Chalk.blueBright(diagnostic.file) + `:` + fileLocText);
  console.log("\n");
  lines.forEach((line, index) => {
    if (!(index > (diagnostic.range.start.line - 5 | 0) && index < (diagnostic.range.end.line + 5 | 0))) {
      return;
    }
    let highlightOnThisLine = index >= diagnostic.range.start.line && index <= diagnostic.range.end.line;
    if (highlightOnThisLine) {
      let highlightStartOffset = index === diagnostic.range.start.line ? diagnostic.range.start.character : 0;
      let highlightEndOffset = index === diagnostic.range.end.line ? diagnostic.range.end.character : line.length;
      let lineText = line.slice(0, highlightStartOffset) + Chalk.bold.red(line.slice(highlightStartOffset, highlightEndOffset)) + line.slice(highlightEndOffset);
      console.log(`  ` + Chalk.bold.red((index + 1 | 0).toString()) + ` ` + Chalk.blackBright(`┆`) + ` ` + lineText);
      return;
    }
    console.log(`  ` + (index + 1 | 0).toString() + ` ` + Chalk.blackBright(`┆`) + ` ` + line);
  });
  console.log("\n  " + diagnostic.message);
}

function printErrors(errors) {
  let fileContentCache = {};
  errors.forEach(error => {
    let content = fileContentCache[error.file];
    let fileContentLines;
    if (content !== undefined) {
      fileContentLines = content;
    } else {
      let contents;
      try {
        contents = Nodefs.readFileSync(error.file).toString("utf8").split(Nodeos.EOL);
      } catch (exn) {
        contents = [];
      }
      fileContentCache[error.file] = contents;
      fileContentLines = contents;
    }
    prettyPrintDiagnostic(fileContentLines, error);
  });
}

let Console;

exports.Chalk = Chalk$1;
exports.Console = Console;
exports.prettyPrintDiagnostic = prettyPrintDiagnostic;
exports.printErrors = printErrors;
/* chalk Not a pure module */
