// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Utils = require("./Utils.js");
let Nodefs = require("node:fs");
let Process = require("process");
let Nodepath = require("node:path");
let Stdlib_JSON = require("@rescript/runtime/lib/js/Stdlib_JSON.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

let generatedSchemaHeader = "/* @generated by ResGraph named schema */";

let generatedInterfaceHeader = "/* @generated */";

let generatedSdlHeader = "# @generated by ResGraph named schema";

function decodeOwnership(raw) {
  return Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(raw), dict => {
    let match = Stdlib_Option.flatMap(dict["name"], Stdlib_JSON.Decode.string);
    let match$1 = Stdlib_Option.flatMap(dict["compilerRoot"], Stdlib_JSON.Decode.string);
    let match$2 = Stdlib_Option.flatMap(dict["outputFolder"], Stdlib_JSON.Decode.string);
    let match$3 = Stdlib_Option.flatMap(dict["moduleName"], Stdlib_JSON.Decode.string);
    let match$4 = Stdlib_Option.flatMap(dict["dumpSchemaSdl"], Stdlib_JSON.Decode.bool);
    if (match !== undefined && match$1 !== undefined && match$2 !== undefined && match$3 !== undefined && match$4 !== undefined) {
      return {
        name: match,
        compilerRoot: match$1,
        outputFolder: match$2,
        moduleName: match$3,
        dumpSchemaSdl: match$4
      };
    }
  });
}

function decodeManifest(raw) {
  return Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(raw), dict => {
    let match = dict["version"];
    let match$1 = Stdlib_Option.flatMap(dict["schemas"], Stdlib_JSON.Decode.array);
    if (match === undefined) {
      return;
    }
    if (match$1 === undefined) {
      return;
    }
    if (JSON.stringify(match) !== "1") {
      return;
    }
    let schemas = match$1.map(decodeOwnership);
    if (schemas.every(Stdlib_Option.isSome)) {
      return {
        version: 1,
        schemas: Stdlib_Array.keepSome(schemas)
      };
    }
  });
}

function manifestPath(configDir) {
  return Nodepath.resolve(configDir, "lib", "resgraph", ".configured-schemas.json");
}

function readManifest(path) {
  if (!Nodefs.existsSync(path)) {
    return;
  }
  try {
    return decodeManifest(JSON.parse(Nodefs.readFileSync(path).toString("utf8")));
  } catch (exn) {
    return;
  }
}

function fileStartsWith(path, prefix) {
  if (!Nodefs.existsSync(path)) {
    return false;
  }
  try {
    return Nodefs.readFileSync(path).toString("utf8").startsWith(prefix);
  } catch (exn) {
    return false;
  }
}

function removeFile(path) {
  if (!Nodefs.existsSync(path)) {
    return;
  }
  try {
    Nodefs.unlinkSync(path);
    return;
  } catch (exn) {
    return;
  }
}

function cleanOwnership(ownership) {
  let schemaSource = Nodepath.resolve(ownership.outputFolder, ownership.moduleName + ".res");
  let schemaInterface = schemaSource + "i";
  if (fileStartsWith(schemaSource, generatedSchemaHeader)) {
    removeFile(schemaSource);
  }
  if (fileStartsWith(schemaInterface, generatedSchemaHeader)) {
    removeFile(schemaInterface);
  }
  if (Nodefs.existsSync(ownership.outputFolder)) {
    let interfacePrefix = ownership.moduleName + "__Interface_";
    try {
      Nodefs.readdirSync(ownership.outputFolder).forEach(fileName => {
        let path = Nodepath.resolve(ownership.outputFolder, fileName);
        if (fileName.startsWith(interfacePrefix) && fileName.endsWith(".res") && fileStartsWith(path, generatedInterfaceHeader)) {
          return removeFile(path);
        }
      });
    } catch (exn) {
      
    }
  }
  let schemaSdl = Nodepath.resolve(ownership.outputFolder, "schema.graphql");
  if (fileStartsWith(schemaSdl, generatedSdlHeader)) {
    return removeFile(schemaSdl);
  }
}

function sameOwnership(left, right) {
  if (left.name === right.name && left.compilerRoot === right.compilerRoot && left.outputFolder === right.outputFolder) {
    return left.moduleName === right.moduleName;
  } else {
    return false;
  }
}

function writeManifest(path, schemas) {
  let temporaryPath = path + "." + Process.pid.toString() + ".tmp";
  try {
    let directory = Nodepath.dirname(path);
    if (!Nodefs.existsSync(directory)) {
      Nodefs.mkdirSync(directory, {
        recursive: true
      });
    }
    let payload = {
      version: 1,
      schemas: schemas
    };
    Nodefs.writeFileSync(temporaryPath, Buffer.from(Stdlib_Option.getOr(JSON.stringify(payload), "")));
    Nodefs.renameSync(temporaryPath, path);
    return;
  } catch (exn) {
    return removeFile(temporaryPath);
  }
}

function sameSchemaSlot(left, right) {
  if (left.compilerRoot === right.compilerRoot) {
    return left.outputFolder === right.outputFolder;
  } else {
    return false;
  }
}

function sameCompilerModule(left, right) {
  if (Utils.portableFilesystemIdentity(left.compilerRoot) === Utils.portableFilesystemIdentity(right.compilerRoot)) {
    return left.moduleName.toLowerCase() === right.moduleName.toLowerCase();
  } else {
    return false;
  }
}

function sync(config, selectedSchemas, configDir) {
  let path = manifestPath(configDir);
  let selectedNames = selectedSchemas.map(schema => schema.name);
  let current = config.legacy ? [] : config.schemas.map(schema => ({
      name: schema.name,
      compilerRoot: Stdlib_Option.getOr(Utils.findCompilerRoot(schema.projectRoot), schema.projectRoot),
      outputFolder: schema.outputFolder,
      moduleName: schema.moduleName,
      dumpSchemaSdl: schema.dumpSchemaSdl
    }));
  let previous = Stdlib_Option.getOr(Stdlib_Option.map(readManifest(path), manifest => manifest.schemas), []);
  let previousForCurrent = currentOwnership => Stdlib_Option.orElse(previous.find(previousOwnership => previousOwnership.name === currentOwnership.name), previous.find(previousOwnership => sameSchemaSlot(previousOwnership, currentOwnership)));
  let ownershipClaimedBySelectedSchema = previousOwnership => current.some(currentOwnership => {
    if (currentOwnership.name !== previousOwnership.name && selectedNames.includes(currentOwnership.name)) {
      return sameCompilerModule(previousOwnership, currentOwnership);
    } else {
      return false;
    }
  });
  previous.forEach(previousOwnership => {
    let successor = Stdlib_Option.orElse(current.find(currentOwnership => currentOwnership.name === previousOwnership.name), current.find(currentOwnership => sameSchemaSlot(previousOwnership, currentOwnership)));
    if (successor !== undefined && !(!sameOwnership(previousOwnership, successor) && selectedNames.includes(successor.name) || ownershipClaimedBySelectedSchema(previousOwnership))) {
      return;
    } else {
      return cleanOwnership(previousOwnership);
    }
  });
  let next = current.map(currentOwnership => {
    let previousOwnership = previousForCurrent(currentOwnership);
    if (previousOwnership !== undefined && !sameOwnership(previousOwnership, currentOwnership) && !selectedNames.includes(currentOwnership.name) && !ownershipClaimedBySelectedSchema(previousOwnership)) {
      return previousOwnership;
    } else {
      return currentOwnership;
    }
  });
  writeManifest(path, next);
}

let manifestVersion = 1;

exports.manifestVersion = manifestVersion;
exports.generatedSchemaHeader = generatedSchemaHeader;
exports.generatedInterfaceHeader = generatedInterfaceHeader;
exports.generatedSdlHeader = generatedSdlHeader;
exports.decodeOwnership = decodeOwnership;
exports.decodeManifest = decodeManifest;
exports.manifestPath = manifestPath;
exports.readManifest = readManifest;
exports.fileStartsWith = fileStartsWith;
exports.removeFile = removeFile;
exports.cleanOwnership = cleanOwnership;
exports.sameOwnership = sameOwnership;
exports.writeManifest = writeManifest;
exports.sameSchemaSlot = sameSchemaSlot;
exports.sameCompilerModule = sameCompilerModule;
exports.sync = sync;
/* Utils Not a pure module */
