type ownership = {
  name: string,
  compilerRoot: string,
  outputFolder: string,
  moduleName: string,
  dumpSchemaSdl: bool,
}

type manifest = {version: int, schemas: array<ownership>}

let manifestVersion = 1
let generatedSchemaHeader = "/* @generated by ResGraph named schema */"
let generatedInterfaceHeader = "/* @generated */"
let generatedSdlHeader = "# @generated by ResGraph named schema"

let decodeOwnership = raw =>
  raw
  ->JSON.Decode.object
  ->Option.flatMap(dict =>
    switch (
      dict->Dict.get("name")->Option.flatMap(JSON.Decode.string),
      dict->Dict.get("compilerRoot")->Option.flatMap(JSON.Decode.string),
      dict->Dict.get("outputFolder")->Option.flatMap(JSON.Decode.string),
      dict->Dict.get("moduleName")->Option.flatMap(JSON.Decode.string),
      dict->Dict.get("dumpSchemaSdl")->Option.flatMap(JSON.Decode.bool),
    ) {
    | (Some(name), Some(compilerRoot), Some(outputFolder), Some(moduleName), Some(dumpSchemaSdl)) =>
      Some({name, compilerRoot, outputFolder, moduleName, dumpSchemaSdl})
    | _ => None
    }
  )

let decodeManifest = raw =>
  raw
  ->JSON.Decode.object
  ->Option.flatMap(dict =>
    switch (
      dict->Dict.get("version"),
      dict->Dict.get("schemas")->Option.flatMap(JSON.Decode.array),
    ) {
    | (Some(version), Some(rawSchemas)) if version->JSON.stringifyAny === Some("1") =>
      let schemas = rawSchemas->Array.map(decodeOwnership)
      if schemas->Array.every(Option.isSome) {
        Some({version: manifestVersion, schemas: schemas->Array.keepSome})
      } else {
        None
      }
    | _ => None
    }
  )

let manifestPath = configDir =>
  Path.resolve([configDir, "lib", "resgraph", ".configured-schemas.json"])

let readManifest = path =>
  if Fs.existsSync(path) {
    try {
      path
      ->Fs.readFileSync
      ->Buffer.toStringWithEncoding(StringEncoding.utf8)
      ->JSON.parseOrThrow
      ->decodeManifest
    } catch {
    | _ => None
    }
  } else {
    None
  }

let fileStartsWith = (path, prefix) =>
  if Fs.existsSync(path) {
    try {
      path
      ->Fs.readFileSync
      ->Buffer.toStringWithEncoding(StringEncoding.utf8)
      ->String.startsWith(prefix)
    } catch {
    | _ => false
    }
  } else {
    false
  }

let removeFile = path => {
  if Fs.existsSync(path) {
    try {
      Fs.unlinkSync(path)
    } catch {
    | _ => ()
    }
  }
}

let cleanOwnership = ownership => {
  let schemaSource = Path.resolve([ownership.outputFolder, ownership.moduleName ++ ".res"])
  let schemaInterface = schemaSource ++ "i"
  if schemaSource->fileStartsWith(generatedSchemaHeader) {
    schemaSource->removeFile
  }
  if schemaInterface->fileStartsWith(generatedSchemaHeader) {
    schemaInterface->removeFile
  }

  if Fs.existsSync(ownership.outputFolder) {
    let interfacePrefix = ownership.moduleName ++ "__Interface_"
    try {
      ownership.outputFolder
      ->Fs.readdirSync
      ->Array.forEach(fileName => {
        let path = Path.resolve([ownership.outputFolder, fileName])
        if (
          fileName->String.startsWith(interfacePrefix) &&
          fileName->String.endsWith(".res") &&
          path->fileStartsWith(generatedInterfaceHeader)
        ) {
          path->removeFile
        }
      })
    } catch {
    | _ => ()
    }
  }

  let schemaSdl = Path.resolve([ownership.outputFolder, "schema.graphql"])
  if schemaSdl->fileStartsWith(generatedSdlHeader) {
    schemaSdl->removeFile
  }
}

let sameOwnership = (left, right) =>
  left.name === right.name &&
  left.compilerRoot === right.compilerRoot &&
  left.outputFolder === right.outputFolder &&
  left.moduleName === right.moduleName

let writeManifest = (path, schemas) => {
  let temporaryPath = path ++ "." ++ Process.process->Process.pid->Int.toString ++ ".tmp"
  try {
    let directory = Path.dirname(path)
    if !Fs.existsSync(directory) {
      Fs.mkdirSyncWith(directory, {recursive: true})
    }
    let payload: manifest = {version: manifestVersion, schemas}
    Fs.writeFileSync(temporaryPath, Buffer.fromString(payload->JSON.stringifyAny->Option.getOr("")))
    Fs.renameSync(~from=temporaryPath, ~to_=path)
  } catch {
  | _ => temporaryPath->removeFile
  }
}

let sameSchemaSlot = (left, right) =>
  left.compilerRoot === right.compilerRoot && left.outputFolder === right.outputFolder

let sameCompilerModule = (left, right) =>
  left.compilerRoot->Utils.portableFilesystemIdentity ===
    right.compilerRoot->Utils.portableFilesystemIdentity &&
    left.moduleName->String.toLowerCase === right.moduleName->String.toLowerCase

let sync = (config: Utils.config, ~selectedSchemas: array<Utils.schemaConfig>, ~configDir) => {
  let path = manifestPath(configDir)
  let selectedNames = selectedSchemas->Array.map(schema => schema.name)
  let current = if config.legacy {
    []
  } else {
    config.schemas->Array.map(schema => {
      name: schema.name,
      compilerRoot: schema.projectRoot->Utils.findCompilerRoot->Option.getOr(schema.projectRoot),
      outputFolder: schema.outputFolder,
      moduleName: schema.moduleName,
      dumpSchemaSdl: schema.dumpSchemaSdl,
    })
  }

  let previous = path->readManifest->Option.map(manifest => manifest.schemas)->Option.getOr([])
  let previousForCurrent = currentOwnership =>
    previous
    ->Array.find(previousOwnership => previousOwnership.name === currentOwnership.name)
    ->Option.orElse(
      previous->Array.find(previousOwnership =>
        sameSchemaSlot(previousOwnership, currentOwnership)
      ),
    )
  let ownershipClaimedBySelectedSchema = previousOwnership =>
    current->Array.some(currentOwnership =>
      currentOwnership.name !== previousOwnership.name &&
      selectedNames->Array.includes(currentOwnership.name) &&
      sameCompilerModule(previousOwnership, currentOwnership)
    )

  previous->Array.forEach(previousOwnership => {
    let successor =
      current
      ->Array.find(currentOwnership => currentOwnership.name === previousOwnership.name)
      ->Option.orElse(
        current->Array.find(currentOwnership =>
          sameSchemaSlot(previousOwnership, currentOwnership)
        ),
      )
    switch successor {
    | None => cleanOwnership(previousOwnership)
    | Some(currentOwnership) =>
      if (
        (!sameOwnership(previousOwnership, currentOwnership) &&
        selectedNames->Array.includes(currentOwnership.name)) ||
          ownershipClaimedBySelectedSchema(previousOwnership)
      ) {
        cleanOwnership(previousOwnership)
      }
    }
  })

  let next = current->Array.map(currentOwnership =>
    switch previousForCurrent(currentOwnership) {
    | Some(previousOwnership)
      if !sameOwnership(previousOwnership, currentOwnership) &&
      !(selectedNames->Array.includes(currentOwnership.name)) &&
      !ownershipClaimedBySelectedSchema(previousOwnership) => previousOwnership
    | _ => currentOwnership
    }
  )
  writeManifest(path, next)
}
