// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Utils = require("./Utils.js");
let Nodefs = require("node:fs");
let Nodepath = require("node:path");
let Stdlib_Exn = require("@rescript/runtime/lib/js/Stdlib_Exn.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let GeneratedArtifacts = require("./GeneratedArtifacts.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

function readFile(relativePath, dir) {
  let path = Nodepath.resolve(dir, relativePath);
  if (!Nodefs.existsSync(path)) {
    return {
      TAG: "Error",
      _0: "FileDoesNotExist"
    };
  }
  try {
    return {
      TAG: "Ok",
      _0: Nodefs.readFileSync(path).toString("utf8")
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === Stdlib_Exn.$$Error) {
      return {
        TAG: "Error",
        _0: {
          TAG: "FileCouldNotBeRead",
          _0: undefined
        }
      };
    }
    throw exn;
  }
}

let validSchemaName = (value => /^[A-Za-z0-9_-]+$/.test(value));

let validModuleName = (value => /^[A-Z][A-Za-z0-9_]*$/.test(value));

let validContextType = (value => /^[A-Z][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+$/.test(value));

function pathIsWithin(path, root) {
  let path$1 = Utils.canonicalPath(path);
  let root$1 = Utils.canonicalPath(root);
  if (path$1 === root$1) {
    return true;
  } else {
    return path$1.startsWith(root$1 + Nodepath.sep);
  }
}

function compilerRoot(projectRoot) {
  return Utils.portableFilesystemIdentity(Stdlib_Option.getOr(Utils.findCompilerRoot(projectRoot), projectRoot));
}

function authorizationArtifactPaths(schema) {
  let authorization = schema.authorization;
  if (authorization !== undefined) {
    return Stdlib_Array.keepSome([
      authorization.manifestPath,
      authorization.baselinePath
    ]);
  } else {
    return [];
  }
}

function artifactFilesystemIdentity(path) {
  return Utils.portableFilesystemIdentity(Nodepath.join(Utils.canonicalPath(Nodepath.dirname(path)), Nodepath.basename(path)));
}

function pathIsGeneratedBySchema(path, schema) {
  let pathIdentity = artifactFilesystemIdentity(path);
  let outputFolderIdentity = Utils.portableFilesystemIdentity(schema.outputFolder);
  let fileName = Nodepath.basename(path);
  let interfacePrefix = (schema.moduleName + "__Interface_").toLowerCase();
  let isInterface = Utils.portableFilesystemIdentity(Nodepath.dirname(path)) === outputFolderIdentity && fileName.toLowerCase().startsWith(interfacePrefix) && fileName.toLowerCase().endsWith(".res");
  let compilerRoot = Stdlib_Option.getOr(Utils.findCompilerRoot(schema.projectRoot), schema.projectRoot);
  let generatedPaths = [
    Nodepath.resolve(schema.outputFolder, schema.moduleName + ".res"),
    Nodepath.resolve(schema.outputFolder, schema.moduleName + ".resi"),
    Nodepath.resolve(schema.outputFolder, "schema.graphql"),
    Nodepath.resolve(compilerRoot, "lib", "resgraph", schema.name + ".state.marshal"),
    Nodepath.resolve(compilerRoot, "lib", "resgraph", schema.name + ".incremental-cache")
  ];
  if (isInterface) {
    return true;
  } else {
    return generatedPaths.some(generatedPath => artifactFilesystemIdentity(generatedPath) === pathIdentity);
  }
}

function validateConfig(config, issues, configDir) {
  let ownershipManifestIdentity = artifactFilesystemIdentity(GeneratedArtifacts.manifestPath(configDir));
  if (Stdlib_Option.isNone(Utils.findSchema(config, config.defaultSchema))) {
    issues.push({
      TAG: "DefaultSchemaDoesNotExist",
      schemaName: config.defaultSchema
    });
  }
  config.schemas.forEach(schema => {
    if (!validSchemaName(schema.name)) {
      issues.push({
        TAG: "InvalidSchemaName",
        schemaName: schema.name
      });
    }
    if (!validModuleName(schema.moduleName)) {
      issues.push({
        TAG: "InvalidModuleName",
        schemaName: schema.name,
        moduleName: schema.moduleName
      });
    }
    if (!validContextType(schema.contextType)) {
      issues.push({
        TAG: "InvalidContextType",
        schemaName: schema.name,
        contextType: schema.contextType
      });
    }
    if (!Nodefs.existsSync(schema.outputFolder)) {
      issues.push({
        TAG: "OutputFolderDoesNotExist",
        schemaName: schema.name,
        path: schema.outputFolder
      });
    }
    if (!Nodefs.existsSync(schema.projectRoot)) {
      issues.push({
        TAG: "ProjectRootDoesNotExist",
        schemaName: schema.name,
        path: schema.projectRoot
      });
    }
    schema.includePaths.forEach(path => {
      if (!Nodefs.existsSync(path)) {
        issues.push({
          TAG: "IncludePathDoesNotExist",
          schemaName: schema.name,
          path: path
        });
      }
      if (!pathIsWithin(path, schema.projectRoot)) {
        issues.push({
          TAG: "IncludePathOutsideProject",
          schemaName: schema.name,
          path: path,
          projectRoot: schema.projectRoot
        });
        return;
      }
    });
    schema.excludePaths.forEach(path => {
      if (!Nodefs.existsSync(path)) {
        issues.push({
          TAG: "ExcludePathDoesNotExist",
          schemaName: schema.name,
          path: path
        });
        return;
      }
    });
    authorizationArtifactPaths(schema).forEach(path => {
      if (artifactFilesystemIdentity(path) === ownershipManifestIdentity) {
        issues.push({
          TAG: "AuthorizationPathCollidesWithOwnershipManifest",
          schemaName: schema.name,
          path: path
        });
        return;
      }
    });
  });
  config.schemas.forEach((schema, index) => {
    config.schemas.forEach((otherSchema, otherIndex) => {
      if (otherIndex > index && Utils.portableFilesystemIdentity(schema.outputFolder) === Utils.portableFilesystemIdentity(otherSchema.outputFolder)) {
        issues.push({
          TAG: "DuplicateOutputFolder",
          firstSchema: schema.name,
          secondSchema: otherSchema.name,
          path: schema.outputFolder
        });
      }
      if (otherIndex > index) {
        let otherAuthorizationPaths = authorizationArtifactPaths(otherSchema);
        let path = authorizationArtifactPaths(schema).find(path => otherAuthorizationPaths.some(otherPath => artifactFilesystemIdentity(path) === artifactFilesystemIdentity(otherPath)));
        if (path !== undefined) {
          issues.push({
            TAG: "DuplicateAuthorizationArtifactPath",
            firstSchema: schema.name,
            secondSchema: otherSchema.name,
            path: path
          });
        }
        authorizationArtifactPaths(schema).forEach(path => {
          if (pathIsGeneratedBySchema(path, otherSchema)) {
            issues.push({
              TAG: "AuthorizationPathCollidesWithGeneratedArtifact",
              authorizationSchema: schema.name,
              generatedSchema: otherSchema.name,
              path: path
            });
            return;
          }
        });
        authorizationArtifactPaths(otherSchema).forEach(path => {
          if (pathIsGeneratedBySchema(path, schema)) {
            issues.push({
              TAG: "AuthorizationPathCollidesWithGeneratedArtifact",
              authorizationSchema: otherSchema.name,
              generatedSchema: schema.name,
              path: path
            });
            return;
          }
        });
      }
      if (otherIndex > index && compilerRoot(schema.projectRoot) === compilerRoot(otherSchema.projectRoot) && schema.moduleName.toLowerCase() === otherSchema.moduleName.toLowerCase()) {
        issues.push({
          TAG: "DuplicateModuleName",
          firstSchema: schema.name,
          secondSchema: otherSchema.name,
          moduleName: schema.moduleName
        });
      }
      if (otherIndex > index && compilerRoot(schema.projectRoot) === compilerRoot(otherSchema.projectRoot) && schema.name.toLowerCase() === otherSchema.name.toLowerCase()) {
        issues.push({
          TAG: "DuplicateSchemaStateName",
          firstSchema: schema.name,
          secondSchema: otherSchema.name
        });
        return;
      }
    });
  });
}

function validateProject(dir) {
  let issues = [];
  let configFileContents = readFile("./resgraph.json", dir);
  if (configFileContents.TAG === "Ok") {
    let config;
    try {
      config = Utils.parseConfig(JSON.parse(configFileContents._0), dir);
    } catch (exn) {
      config = undefined;
    }
    if (config !== undefined) {
      validateConfig(config, issues, dir);
    } else {
      issues.push("ConfigFileIssue");
    }
  } else {
    issues.push("MissingConfigFile");
  }
  return issues;
}

function printProjectIssues(issues) {
  console.error("⛔ One or more issues was encountered with this ResGraph project.\n");
  issues.forEach(issue => {
    if (typeof issue !== "object") {
      if (issue === "MissingConfigFile") {
        console.error(`- 🚫 The file "resgraph.json" does not exist in this project root. Please create it and add + configure the content below to your liking:
{
  "src": "./src",
  "outputFolder": "./src/__generated__"
}`);
        return;
      }
      console.error(`- 🚫 "resgraph.json" could not be parsed. Please check its schema configuration.`);
      return;
    } else {
      switch (issue.TAG) {
        case "OutputFolderDoesNotExist" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" outputFolder "` + issue.path + `" does not exist or cannot be accessed.`);
          return;
        case "ProjectRootDoesNotExist" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" projectRoot "` + issue.path + `" does not exist or cannot be accessed.`);
          return;
        case "IncludePathDoesNotExist" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" include path "` + issue.path + `" does not exist or cannot be accessed.`);
          return;
        case "ExcludePathDoesNotExist" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" exclude path "` + issue.path + `" does not exist or cannot be accessed.`);
          return;
        case "DuplicateOutputFolder" :
          console.error(`- 🚫 Schemas "` + issue.firstSchema + `" and "` + issue.secondSchema + `" use the same outputFolder "` + issue.path + `".`);
          return;
        case "DuplicateAuthorizationArtifactPath" :
          console.error(`- 🚫 Schemas "` + issue.firstSchema + `" and "` + issue.secondSchema + `" use the same authorization manifest or baseline path "` + issue.path + `".`);
          return;
        case "AuthorizationPathCollidesWithGeneratedArtifact" :
          console.error(`- 🚫 Schemas "` + issue.authorizationSchema + `" and "` + issue.generatedSchema + `" configure authorization and generated artifacts at the same path "` + issue.path + `".`);
          return;
        case "AuthorizationPathCollidesWithOwnershipManifest" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" configures an authorization artifact at the reserved schema ownership manifest path "` + issue.path + `".`);
          return;
        case "DuplicateModuleName" :
          console.error(`- 🚫 Schemas "` + issue.firstSchema + `" and "` + issue.secondSchema + `" use moduleName "` + issue.moduleName + `" in the same ReScript package.`);
          return;
        case "DuplicateSchemaStateName" :
          console.error(`- 🚫 Schemas "` + issue.firstSchema + `" and "` + issue.secondSchema + `" have names that collide on case-insensitive filesystems in the same ReScript package.`);
          return;
        case "DefaultSchemaDoesNotExist" :
          console.error(`- 🚫 defaultSchema "` + issue.schemaName + `" does not name a configured schema.`);
          return;
        case "InvalidSchemaName" :
          console.error(`- 🚫 Schema name "` + issue.schemaName + `" may contain only letters, numbers, underscores, and hyphens.`);
          return;
        case "InvalidModuleName" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" moduleName "` + issue.moduleName + `" is not a valid ReScript module name.`);
          return;
        case "InvalidContextType" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" contextType "` + issue.contextType + `" is not a valid qualified ReScript type.`);
          return;
        case "IncludePathOutsideProject" :
          console.error(`- 🚫 Schema "` + issue.schemaName + `" include path "` + issue.path + `" is outside projectRoot "` + issue.projectRoot + `".`);
          return;
      }
    }
  });
}

let Console;

let JsExn;

exports.Console = Console;
exports.JsExn = JsExn;
exports.readFile = readFile;
exports.validSchemaName = validSchemaName;
exports.validModuleName = validModuleName;
exports.validContextType = validContextType;
exports.pathIsWithin = pathIsWithin;
exports.compilerRoot = compilerRoot;
exports.authorizationArtifactPaths = authorizationArtifactPaths;
exports.artifactFilesystemIdentity = artifactFilesystemIdentity;
exports.pathIsGeneratedBySchema = pathIsGeneratedBySchema;
exports.validateConfig = validateConfig;
exports.validateProject = validateProject;
exports.printProjectIssues = printProjectIssues;
/* Utils Not a pure module */
