// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Url = require("url");
let Utils = require("./Utils.js");
let Stdlib = require("@rescript/runtime/lib/js/Stdlib.js");
let Nodefs = require("node:fs");
let Nodepath = require("node:path");
let InitProject = require("./InitProject.js");
let Stdlib_Dict = require("@rescript/runtime/lib/js/Stdlib_Dict.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let VscodeJsonrpc = require("vscode-jsonrpc");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let GeneratedArtifacts = require("./GeneratedArtifacts.js");
let LspCompleteGraphQL = require("./LspCompleteGraphQL.js");
let MessagesJs = require("vscode-jsonrpc/lib/messages.js");

let initialized = {
  contents: false
};

let shutdownRequestAlreadyReceived = {
  contents: false
};

function log(prim) {
  console.error(prim);
}

let jsonrpcVersion = "2.0";

function decodeLspMessage(msg) {
  let match = msg.method;
  if (match === "textDocument/definition") {
    return {
      TAG: "Definition",
      _0: msg.params
    };
  } else if (match === "textDocument/completion") {
    return {
      TAG: "Completion",
      _0: msg.params
    };
  } else if (match === "textDocument/didClose") {
    return {
      TAG: "DidCloseTextDocumentNotification",
      _0: msg.params
    };
  } else if (match === "textDocument/documentLink") {
    return {
      TAG: "DocumentLinks",
      _0: msg.params
    };
  } else if (match === "textDocument/didChange") {
    return {
      TAG: "DidChangeTextDocumentNotification",
      _0: msg.params
    };
  } else if (match === "textDocument/didOpen") {
    return {
      TAG: "DidOpenTextDocumentNotification",
      _0: msg.params
    };
  } else if (match === "textDocument/hover") {
    return {
      TAG: "Hover",
      _0: msg.params
    };
  } else if (match === "textDocument/codeLens") {
    return {
      TAG: "CodeLens",
      _0: msg.params
    };
  } else if (match === "textDocument/codeAction") {
    return {
      TAG: "CodeAction",
      _0: msg.params
    };
  } else {
    return "UnmappedMessage";
  }
}

let LspMessage = {
  decodeLspMessage: decodeLspMessage
};

function asMessage(notification) {
  return {
    jsonrpc: jsonrpcVersion,
    method: "textDocument/publishDiagnostics",
    params: notification._0
  };
}

let Notification = {
  asMessage: asMessage
};

function codeToInt(code) {
  if (code === "ServerNotInitialized") {
    return -32002;
  } else {
    return -32600;
  }
}

function make(code, message) {
  return {
    code: codeToInt(code),
    message: message
  };
}

let $$Error = {
  make: make
};

function make$1(textDocumentSyncOpt, hoverProviderOpt, completionProvider, codeLensProviderOpt, documentLinkProviderOpt, codeActionProviderOpt, definitionProviderOpt, param) {
  let hoverProvider = hoverProviderOpt !== undefined ? hoverProviderOpt : false;
  let codeLensProvider = codeLensProviderOpt !== undefined ? codeLensProviderOpt : false;
  let documentLinkProvider = documentLinkProviderOpt !== undefined ? documentLinkProviderOpt : false;
  let codeActionProvider = codeActionProviderOpt !== undefined ? codeActionProviderOpt : false;
  let definitionProvider = definitionProviderOpt !== undefined ? definitionProviderOpt : false;
  return {
    capabilities: {
      textDocumentSync: 1,
      hoverProvider: hoverProvider,
      completionProvider: completionProvider,
      codeLensProvider: codeLensProvider,
      documentLinkProvider: documentLinkProvider,
      codeActionProvider: codeActionProvider,
      definitionProvider: definitionProvider
    }
  };
}

let InitializeResult = {
  make: make$1
};

function $$null() {
  return null;
}

let Result = {
  $$null: $$null
};

function make$2(id, error, result, param) {
  return {
    jsonrpc: jsonrpcVersion,
    id: id,
    error: error,
    result: result
  };
}

let Response = {
  make: make$2
};

let Message = {
  jsonrpcVersion: jsonrpcVersion,
  LspMessage: LspMessage,
  Notification: Notification,
  $$Error: $$Error,
  InitializeResult: InitializeResult,
  Result: Result,
  Response: Response
};

function defaultSendFn(param) {
  
}

let sendFn = {
  contents: defaultSendFn
};

function send(msg) {
  sendFn.contents(msg);
}

let StreamMessageWriter = {};

let StreamMessageReader = {};

let Rpc = {
  StreamMessageWriter: StreamMessageWriter,
  StreamMessageReader: StreamMessageReader
};

function start(mode, configFilePath) {
  let msg = Utils.readConfigFromDir(configFilePath);
  let config;
  if (msg.TAG === "Ok") {
    config = msg._0;
  } else {
    let msg$1 = msg._0;
    console.error(msg$1);
    config = Stdlib.panic(msg$1);
  }
  let configIssues = [];
  InitProject.validateConfig(config, configIssues, configFilePath);
  if (configIssues.length !== 0) {
    InitProject.printProjectIssues(configIssues);
    Stdlib.panic("Invalid ResGraph configuration.");
  }
  GeneratedArtifacts.sync(config, config.schemas, configFilePath);
  let currentResults = {};
  let resFilesCache = {};
  let filesWithDiagnostics = {
    contents: []
  };
  let publishDiagnostics = () => {
    let filesWithDiagnosticsAtLastPublish = filesWithDiagnostics.contents.slice();
    let errorsByFile = {};
    config.schemas.forEach(schema => {
      let match = currentResults[schema.name];
      if (match === undefined) {
        return;
      }
      if (typeof match !== "object") {
        return;
      }
      if (match.status !== "Error") {
        return;
      }
      match.errors.forEach(error => {
        let errorsForFile = Stdlib_Option.getOr(errorsByFile[error.file], []);
        errorsByFile[error.file] = errorsForFile.concat([error]);
      });
    });
    let currentFilesWithDiagnostics = Object.entries(errorsByFile).map(param => {
      let file = param[0];
      sendFn.contents(asMessage({
        TAG: "PublishDiagnostics",
        _0: {
          uri: file,
          diagnostics: param[1].map(error => ({
            range: error.range,
            message: error.message,
            source: "ResGraph"
          }))
        }
      }));
      return file;
    });
    filesWithDiagnostics.contents = currentFilesWithDiagnostics;
    filesWithDiagnosticsAtLastPublish.forEach(fileName => {
      if (!currentFilesWithDiagnostics.includes(fileName)) {
        return sendFn.contents(asMessage({
          TAG: "PublishDiagnostics",
          _0: {
            uri: fileName,
            diagnostics: []
          }
        }));
      }
    });
  };
  let watchers = config.schemas.map(schema => Utils.setupWatcher((schema, result) => {
    if (typeof result !== "object") {
      return;
    }
    currentResults[schema.name] = result._0;
    publishDiagnostics();
  }, _schema => {}, schema));
  let openedFile = (uri, text) => {
    console.error(`opened ` + uri);
    let match = Nodepath.extname(uri);
    if (match !== ".res") {
      return;
    }
    resFilesCache[uri] = text;
  };
  let updateOpenedFile = (uri, text) => {
    if (Nodepath.extname(uri) === ".res" && Stdlib_Option.isSome(resFilesCache[uri])) {
      resFilesCache[uri] = text;
      return;
    }
  };
  let onMessage = msg => {
    if (MessagesJs.isNotificationMessage(msg)) {
      let match = initialized.contents;
      let match$1 = msg.method;
      if (match) {
        if (match$1 === "exit") {
          if (shutdownRequestAlreadyReceived.contents === true) {
            process.exit(0);
          } else {
            process.exit(1);
          }
        } else {
          let params = decodeLspMessage(msg);
          if (typeof params === "object") {
            switch (params.TAG) {
              case "DidOpenTextDocumentNotification" :
                let params$1 = params._0;
                openedFile(params$1.textDocument.uri, params$1.textDocument.text);
                break;
              case "DidChangeTextDocumentNotification" :
                let params$2 = params._0;
                let match$2 = params$2.contentChanges.slice().pop();
                if (match$2 !== undefined) {
                  updateOpenedFile(params$2.textDocument.uri, match$2.text);
                }
                break;
              case "DidCloseTextDocumentNotification" :
                Stdlib_Dict.$$delete(resFilesCache, params._0.textDocument.uri);
                break;
            }
          }
        }
        return;
      }
      console.error("Could not handle notification message.");
      return;
    }
    if (!MessagesJs.isRequestMessage(msg)) {
      return;
    }
    let sendNullresponse = () => sendFn.contents(make$2(msg.id, undefined, null, undefined));
    let match$3 = initialized.contents;
    let match$4 = msg.method;
    if (!match$3) {
      if (match$4 !== "initialize") {
        return sendFn.contents(make$2(msg.id, {
          code: -32002,
          message: `Server not initialized.`
        }, undefined, undefined));
      } else if (match$4 === "initialize") {
        initialized.contents = true;
        return sendFn.contents(make$2(msg.id, undefined, Primitive_option.some(make$1("Full", true, {
          triggerCharacters: [
            "@",
            "~"
          ]
        }, undefined, undefined, undefined, true, undefined)), undefined));
      } else {
        return sendFn.contents(make$2(msg.id, {
          code: -32600,
          message: `Unrecognized editor request.`
        }, undefined, undefined));
      }
    }
    if (match$4 === "shutdown") {
      if (shutdownRequestAlreadyReceived.contents === true) {
        return sendFn.contents(make$2(msg.id, {
          code: -32600,
          message: `Language server already received the shutdown request.`
        }, undefined, undefined));
      } else {
        shutdownRequestAlreadyReceived.contents = true;
        watchers.forEach(watcher => {
          watcher.close();
        });
        return sendFn.contents(make$2(msg.id, undefined, null, undefined));
      }
    }
    if (match$4 === "initialize") {
      return sendNullresponse();
    }
    let params$3 = decodeLspMessage(msg);
    if (typeof params$3 === "object") {
      switch (params$3.TAG) {
        case "Hover" :
          let params$4 = params$3._0;
          let filePath = Url.fileURLToPath(params$4.textDocument.uri);
          let match$5 = Nodepath.extname(params$4.textDocument.uri);
          let exit = 0;
          switch (match$5) {
            case ".graphql" :
              let stateName = Stdlib_Option.flatMap(Utils.schemaForGraphqlFile(config, filePath), schema => schema.stateName);
              let hover = LspCompleteGraphQL.hoverAtPos(filePath, params$4.position, stateName);
              let result = hover !== undefined ? hover : null;
              return sendFn.contents(make$2(msg.id, undefined, Primitive_option.some(result), undefined));
            case ".res" :
            case ".resi" :
              exit = 2;
              break;
            default:
              return sendNullresponse();
          }
          if (exit === 2) {
            let match$6 = Utils.callPrivateCli({
              TAG: "Hover",
              filePath: filePath,
              position: params$4.position
            });
            let result$1;
            result$1 = typeof match$6 !== "object" || match$6.status !== "Hover" ? null : match$6.item;
            return sendFn.contents(make$2(msg.id, undefined, Primitive_option.some(result$1), undefined));
          }
          break;
        case "Completion" :
          let params$5 = params$3._0;
          let match$7 = Nodepath.extname(params$5.textDocument.uri);
          if (match$7 === ".graphql") {
            return sendFn.contents(make$2(msg.id, undefined, null, undefined));
          }
          let code = resFilesCache[params$5.textDocument.uri];
          if (code === undefined) {
            return sendFn.contents(make$2(msg.id, undefined, null, undefined));
          }
          let filePath$1 = Url.fileURLToPath(params$5.textDocument.uri);
          let tmpname = Utils.createFileInTempDir(undefined);
          Nodefs.writeFileSync(tmpname, Buffer.from(code), {
            encoding: "utf-8"
          });
          let stateName$1 = Stdlib_Option.flatMap(Utils.schemaForFile(config, filePath$1), schema => schema.stateName);
          let match$8 = Utils.callPrivateCli({
            TAG: "Completion",
            filePath: filePath$1,
            position: params$5.position,
            tmpname: tmpname,
            stateName: stateName$1
          });
          let result$2;
          result$2 = typeof match$8 !== "object" || match$8.status !== "Completion" ? null : match$8.items;
          return sendFn.contents(make$2(msg.id, undefined, Primitive_option.some(result$2), undefined));
        case "Definition" :
          let params$6 = params$3._0;
          let filePath$2 = Url.fileURLToPath(params$6.textDocument.uri);
          let match$9 = Nodepath.extname(params$6.textDocument.uri);
          if (match$9 !== ".graphql") {
            return sendNullresponse();
          }
          let stateName$2 = Stdlib_Option.flatMap(Utils.schemaForGraphqlFile(config, filePath$2), schema => schema.stateName);
          let definition = LspCompleteGraphQL.definitionAtPos(filePath$2, params$6.position, stateName$2);
          let result$3 = definition !== undefined ? definition : null;
          return sendFn.contents(make$2(msg.id, undefined, Primitive_option.some(result$3), undefined));
      }
    }
    sendFn.contents(make$2(msg.id, {
      code: -32600,
      message: `Unrecognized editor request.`
    }, undefined, undefined));
  };
  if (mode === "NodeRpc") {
    sendFn.contents = prim => {
      process.send(prim);
    };
    process.on("message", onMessage);
    console.error(`Starting LSP in Node RPC.`);
    return;
  }
  let writer = new VscodeJsonrpc.StreamMessageWriter(process.stdout);
  let reader = new VscodeJsonrpc.StreamMessageReader(process.stdin);
  sendFn.contents = msg => {
    writer.write(msg);
  };
  reader.listen(onMessage);
  console.error(`Starting LSP in stdio mode.`);
}

process.on("unhandledRejection", (err, _p) => {
  console.error(err);
});

let Console;

exports.initialized = initialized;
exports.shutdownRequestAlreadyReceived = shutdownRequestAlreadyReceived;
exports.Console = Console;
exports.log = log;
exports.Message = Message;
exports.defaultSendFn = defaultSendFn;
exports.sendFn = sendFn;
exports.send = send;
exports.Rpc = Rpc;
exports.start = start;
/*  Not a pure module */
