// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Utils = require("./Utils.js");
let Nodefs = require("node:fs");
let Stdlib_Exn = require("@rescript/runtime/lib/js/Stdlib_Exn.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");
let GraphqlLanguageService = require("graphql-language-service");

function findOwner(state) {
  let match = state.prevState;
  if (match == null) {
    return;
  }
  let name = match.name;
  if (name == null) {
    return;
  }
  let kind = match.kind;
  if (kind == null) {
    return;
  } else {
    return [
      kind,
      name
    ];
  }
}

function findLookupValue(token) {
  let state = token.state;
  let name = state.name;
  if (name == null) {
    return;
  }
  let match = state.kind;
  if (match == null) {
    return;
  }
  switch (match) {
    case "FieldDef" :
      let match$1 = findOwner(state);
      if (match$1 !== undefined) {
        return {
          TAG: "Field",
          ownerTypeName: match$1[1],
          fieldName: name
        };
      } else {
        return;
      }
    case "NamedType" :
    case "ScalarDef" :
    case "ObjectTypeDef" :
    case "InterfaceDef" :
    case "UnionDef" :
    case "EnumDef" :
    case "InputDef" :
      return {
        TAG: "Typename",
        _0: name
      };
    default:
      return;
  }
}

function hoverAtPos(path, pos, stateName) {
  try {
    let fileContents = Nodefs.readFileSync(path).toString("utf8");
    let match = findLookupValue(GraphqlLanguageService.getTokenAtPosition(fileContents, pos));
    if (match === undefined) {
      return;
    }
    if (match.TAG === "Typename") {
      let match$1 = Utils.callPrivateCli({
        TAG: "HoverGraphQL",
        filePath: path,
        hoverHint: match._0,
        stateName: stateName
      });
      if (typeof match$1 !== "object" || match$1.status !== "Hover") {
        return;
      } else {
        return match$1.item;
      }
    }
    let match$2 = Utils.callPrivateCli({
      TAG: "HoverGraphQL",
      filePath: path,
      hoverHint: match.ownerTypeName + `.` + match.fieldName,
      stateName: stateName
    });
    if (typeof match$2 !== "object" || match$2.status !== "Hover") {
      return;
    } else {
      return match$2.item;
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === Stdlib_Exn.$$Error) {
      console.error(e._1);
      return;
    }
    throw e;
  }
}

function definitionAtPos(path, pos, stateName) {
  try {
    let fileContents = Nodefs.readFileSync(path).toString("utf8");
    let match = findLookupValue(GraphqlLanguageService.getTokenAtPosition(fileContents, pos));
    if (match === undefined) {
      return;
    }
    if (match.TAG === "Typename") {
      let match$1 = Utils.callPrivateCli({
        TAG: "Definition",
        filePath: path,
        definitionHint: match._0,
        stateName: stateName
      });
      if (typeof match$1 !== "object" || match$1.status !== "Definition") {
        return;
      } else {
        return match$1.item;
      }
    }
    let match$2 = Utils.callPrivateCli({
      TAG: "Definition",
      filePath: path,
      definitionHint: match.ownerTypeName + `.` + match.fieldName,
      stateName: stateName
    });
    if (typeof match$2 !== "object" || match$2.status !== "Definition") {
      return;
    } else {
      return match$2.item;
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === Stdlib_Exn.$$Error) {
      console.error(e._1);
      return;
    }
    throw e;
  }
}

let Console;

exports.Console = Console;
exports.findOwner = findOwner;
exports.findLookupValue = findLookupValue;
exports.hoverAtPos = hoverAtPos;
exports.definitionAtPos = definitionAtPos;
/* Utils Not a pure module */
