// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function makeDiagnostic(range, message) {
  return {
    range: range,
    message: message,
    source: "RescriptRelayRouter"
  };
}

function makeHover(message, loc) {
  return {
    contents: {
      kind: "markdown",
      value: message
    },
    range: loc
  };
}

function completionItemToInt(item) {
  switch (item) {
    case "Text" :
      return 1;
    case "Method" :
      return 2;
    case "Function" :
      return 3;
    case "Constructor" :
      return 4;
    case "Field" :
      return 5;
    case "Variable" :
      return 6;
    case "Class" :
      return 7;
    case "Interface" :
      return 8;
    case "Module" :
      return 9;
    case "Property" :
      return 10;
    case "Unit" :
      return 11;
    case "Value" :
      return 12;
    case "Enum" :
      return 13;
    case "Keyword" :
      return 14;
    case "Snippet" :
      return 15;
    case "Color" :
      return 16;
    case "File" :
      return 17;
    case "Reference" :
      return 18;
    case "Folder" :
      return 19;
    case "EnumMember" :
      return 20;
    case "Constant" :
      return 21;
    case "Struct" :
      return 22;
    case "Event" :
      return 23;
    case "Operator" :
      return 24;
    case "TypeParameter" :
      return 25;
  }
}

function makeCompletionItem(label, kind) {
  return {
    label: label,
    kind: kind
  };
}

function codeActionKindToString(kind) {
  switch (kind) {
    case "Empty" :
      return "";
    case "QuickFix" :
      return "quickfix";
    case "Refactor" :
      return "refactor";
    case "RefactorExtract" :
      return "refactor.extract";
    case "RefactorInline" :
      return "refactor.inline";
    case "RefactorRewrite" :
      return "refactor.rewrite";
    case "Source" :
      return "source";
    case "SourceOrganizeImports" :
      return "source.organizeImports";
    case "SourceFixAll" :
      return "source.fixAll";
  }
}

function make(uri, overwrite, ignoreIfExists, param) {
  return {
    kind: "create",
    uri: uri,
    options: {
      overwrite: overwrite,
      ignoreIfExists: ignoreIfExists
    }
  };
}

let CreateFile = {
  make: make
};

function make$1(textDocumentUri, edits) {
  return {
    textDocument: {
      uri: textDocumentUri
    },
    edits: edits
  };
}

let TextDocumentEdit = {
  make: make$1
};

let DocumentChange = {
  CreateFile: CreateFile,
  TextDocumentEdit: TextDocumentEdit
};

function makeOpenFileCommand(title, fileUri) {
  return {
    title: title,
    command: `vscode.open`,
    arguments: [fileUri]
  };
}

function makeOpenFileAtPosCommand(title, fileUri, pos) {
  return {
    title: title,
    command: `vscode-rescript-relay.open-pos-in-doc`,
    arguments: [
      fileUri,
      pos.line.toString(),
      pos.character.toString()
    ]
  };
}

function makeOpenRouteDefinitionsCommand(title, routes) {
  return {
    title: title,
    command: `vscode-rescript-relay.open-route-definitions`,
    arguments: routes.map(r => r.sourceFilePath + `;` + r.routeName + `;` + r.loc.line.toString() + `;` + r.loc.character.toString() + `;` + r.routeRendererFilePath)
  };
}

function makeTextOnlyCommand(title) {
  return {
    title: title,
    command: "",
    arguments: undefined
  };
}

let Command = {
  makeOpenFileCommand: makeOpenFileCommand,
  makeOpenFileAtPosCommand: makeOpenFileAtPosCommand,
  makeOpenRouteDefinitionsCommand: makeOpenRouteDefinitionsCommand,
  makeTextOnlyCommand: makeTextOnlyCommand
};

function makeCodeLensItem(range, command) {
  return {
    range: range,
    command: command
  };
}

function makeDocumentLink(range, fileUri, tooltip, param) {
  return {
    range: range,
    target: fileUri,
    tooltip: tooltip
  };
}

exports.makeDiagnostic = makeDiagnostic;
exports.makeHover = makeHover;
exports.completionItemToInt = completionItemToInt;
exports.makeCompletionItem = makeCompletionItem;
exports.codeActionKindToString = codeActionKindToString;
exports.DocumentChange = DocumentChange;
exports.Command = Command;
exports.makeCodeLensItem = makeCodeLensItem;
exports.makeDocumentLink = makeDocumentLink;
/* No side effect */
