// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Url = require("url");
let Nodefs = require("node:fs");
let Nodeos = require("node:os");
let Process = require("process");
let Chokidar = require("chokidar").default;
let Nodepath = require("node:path");
let Belt_Array = require("@rescript/runtime/lib/js/Belt_Array.js");
let Stdlib_Exn = require("@rescript/runtime/lib/js/Stdlib_Exn.js");
let Stdlib_JSON = require("@rescript/runtime/lib/js/Stdlib_JSON.js");
let Stdlib_Lazy = require("@rescript/runtime/lib/js/Stdlib_Lazy.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Float = require("@rescript/runtime/lib/js/Stdlib_Float.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let Nodechild_process = require("node:child_process");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let isWindows = (process.platform === "win32");

function canonicalPath(path) {
  let canonical;
  try {
    canonical = Nodefs.realpathSync(path);
  } catch (exn) {
    canonical = path;
  }
  if (isWindows) {
    return canonical.toLowerCase();
  } else {
    return canonical;
  }
}

function portableFilesystemIdentity(path) {
  return canonicalPath(path).toLowerCase();
}

function resolveRelative(path, baseDir) {
  return Nodepath.resolve(baseDir, path);
}

function optionStringToArray(value) {
  if (value !== undefined) {
    return [Primitive_option.valFromOption(value)];
  } else {
    return [];
  }
}

function privateCliCallToArgs(call) {
  switch (call.TAG) {
    case "GenerateSchema" :
      let match = call._0;
      let stateName = match.stateName;
      let authorization = match.authorization;
      let outputFolder = match.outputFolder;
      let baseArgs = [
        "generate-schema",
        match.projectRoot,
        outputFolder,
        match.dumpSchemaSdl ? "true" : "false"
      ];
      let authorizationArgs;
      if (authorization !== undefined) {
        let match$1 = authorization.mode;
        let tmp;
        tmp = match$1 === "Required" ? "required" : "baseline";
        authorizationArgs = [
          tmp,
          Stdlib_Option.getOr(authorization.onForbidden, "-"),
          Stdlib_Option.getOr(authorization.manifestPath, "-"),
          Stdlib_Option.getOr(authorization.baselinePath, "-")
        ];
      } else {
        authorizationArgs = [];
      }
      let args = baseArgs.concat(authorizationArgs);
      if (stateName !== undefined) {
        return args.concat([
          "--schema",
          stateName,
          "--module",
          match.moduleName,
          "--context",
          match.contextType
        ]).concat(match.includePaths.flatMap(path => [
          "--include",
          path
        ])).concat(match.excludePaths.concat([outputFolder]).flatMap(path => [
          "--exclude",
          path
        ]));
      } else {
        return args;
      }
    case "Completion" :
      let position = call.position;
      return Belt_Array.concatMany([
        [
          "completion",
          call.filePath,
          position.line.toString(),
          position.character.toString(),
          call.tmpname
        ],
        optionStringToArray(call.stateName)
      ]);
    case "Hover" :
      let position$1 = call.position;
      return Belt_Array.concatMany([
        [
          "hover",
          call.filePath,
          position$1.line.toString(),
          position$1.character.toString()
        ],
        optionStringToArray(call.stateName)
      ]);
    case "HoverGraphQL" :
      return Belt_Array.concatMany([
        [
          "hover-graphql",
          call.filePath,
          call.hoverHint
        ],
        optionStringToArray(call.stateName)
      ]);
    case "Definition" :
      return Belt_Array.concatMany([
        [
          "definition-graphql",
          call.filePath,
          call.definitionHint
        ],
        optionStringToArray(call.stateName)
      ]);
    case "FindDefinition" :
      return Belt_Array.concatMany([
        [
          "find-definition",
          call.filePath,
          call.definitionHint
        ],
        optionStringToArray(call.stateName)
      ]);
  }
}

let devBinLocation = "../bin/dev/resgraph.exe";

let hasDevBin = Stdlib_Lazy.make(() => Nodefs.existsSync(new Url.URL(devBinLocation, import.meta.url).pathname));

function callPrivateCli(command) {
  let hasDevBin$1 = Stdlib_Lazy.get(hasDevBin);
  let binLocation;
  if (hasDevBin$1) {
    binLocation = devBinLocation;
  } else {
    let match = Nodeos.platform();
    let match$1 = Nodeos.arch();
    let tmp = match === "darwin" && match$1 === "arm64" ? "darwinarm64" : match;
    binLocation = "../bin/" + tmp + "/resgraph.exe";
  }
  return JSON.parse(Nodechild_process.execFileSync(new Url.URL(binLocation, import.meta.url).pathname, privateCliCallToArgs(command), {
    maxBuffer: Infinity
  }).toString());
}

function formatFindDefinitionText(item) {
  let match = item.range;
  let end_ = match.end;
  let start = match.start;
  return `path: ` + item.path + `\nkind: ` + item.kind + `\nfile: ` + item.file + `\nrange: ` + start.line.toString() + `:` + start.column.toString() + `-` + end_.line.toString() + `:` + end_.column.toString();
}

function stringifyFindDefinitionJson(item) {
  let payload_path = item.path;
  let payload_kind = item.kind;
  let payload_file = item.file;
  let payload_range = item.range;
  let payload = {
    path: payload_path,
    kind: payload_kind,
    file: payload_file,
    range: payload_range
  };
  return JSON.stringify(payload);
}

function stringifyFindDefinitionError(error) {
  let payload = {
    error: error
  };
  return JSON.stringify(payload);
}

function getLastBuiltFromCompilerLog(compilerLogPath) {
  let compilerLogContents = Nodefs.readFileSync(compilerLogPath).toString().split(Nodeos.EOL);
  let statusLine = Stdlib_Option.getOr(compilerLogContents[compilerLogContents.length - 2 | 0], "");
  if (statusLine.startsWith("#Done(")) {
    return Stdlib_Float.fromString(statusLine.split("#Done(")[1].split(")")[0]);
  }
}

function runIfCompilerDone(fn, compilerLogPath, lastCompletedBuild) {
  try {
    let buildMarker = getLastBuiltFromCompilerLog(compilerLogPath);
    if (buildMarker === undefined) {
      return;
    }
    let lastBuildMarker = lastCompletedBuild.contents;
    if (lastBuildMarker !== undefined && lastBuildMarker === buildMarker) {
      return;
    } else {
      lastCompletedBuild.contents = buildMarker;
      return fn();
    }
  } catch (exn) {
    return;
  }
}

function hasProjectConfig(root) {
  if (Nodefs.existsSync(Nodepath.join(root, "rescript.json"))) {
    return true;
  } else {
    return Nodefs.existsSync(Nodepath.join(root, "bsconfig.json"));
  }
}

function findCompilerRoot(_path) {
  while (true) {
    let path = _path;
    if (hasProjectConfig(path)) {
      return path;
    }
    let parent = Nodepath.dirname(path);
    if (parent === path) {
      return;
    }
    _path = parent;
    continue;
  };
}

function setupWatcher(onResult, onStartRebuild, config) {
  let compilerRoot = Stdlib_Option.getOr(findCompilerRoot(config.projectRoot), config.projectRoot);
  let compilerLogPath = Nodepath.resolve(compilerRoot, "./lib/bs/.compiler.log");
  let lastCompletedBuild = {
    contents: undefined
  };
  let generateSchema = () => {
    onStartRebuild(config);
    try {
      let res = callPrivateCli({
        TAG: "GenerateSchema",
        _0: config
      });
      return onResult(config, {
        TAG: "GeneratorResult",
        _0: res
      });
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error(`[` + config.name + `] Generator process failed.`);
        console.error(error._1);
        return onResult(config, "GeneratorProcessFailure");
      } else {
        console.error(`[` + config.name + `] Generator process failed.`);
        return onResult(config, "GeneratorProcessFailure");
      }
    }
  };
  let tmp;
  try {
    tmp = getLastBuiltFromCompilerLog(compilerLogPath);
  } catch (exn) {
    tmp = undefined;
  }
  lastCompletedBuild.contents = tmp;
  let compilerWatcher = Chokidar.watch(compilerLogPath).on("change", compilerLogPath => runIfCompilerDone(generateSchema, compilerLogPath, lastCompletedBuild)).on("unlink", compilerLogPath => runIfCompilerDone(generateSchema, compilerLogPath, lastCompletedBuild));
  generateSchema();
  runIfCompilerDone(generateSchema, compilerLogPath, lastCompletedBuild);
  return compilerWatcher;
}

let tempFilePrefix = "resgraph_support_file_" + Process.pid.toString() + "_";

let tempFileId = {
  contents: 0
};

function createFileInTempDir(extensionOpt) {
  let extension = extensionOpt !== undefined ? extensionOpt : "";
  let tempFileName = tempFilePrefix + tempFileId.contents.toString() + extension;
  tempFileId.contents = tempFileId.contents + 1 | 0;
  return Nodepath.join(Nodeos.tmpdir(), tempFileName);
}

function parseOptionalString(dict, key) {
  let value = dict[key];
  if (value !== undefined) {
    return Stdlib_Option.map(Stdlib_JSON.Decode.string(value), value => value);
  } else {
    return Primitive_option.some(undefined);
  }
}

function parseAuthorizationConfig(dict, baseDir) {
  let value = dict["authorization"];
  if (value !== undefined) {
    return Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(value), authorization => {
      let match = Stdlib_Option.flatMap(authorization["mode"], Stdlib_JSON.Decode.string);
      let match$1 = parseOptionalString(authorization, "onForbidden");
      let match$2 = parseOptionalString(authorization, "manifestPath");
      let match$3 = parseOptionalString(authorization, "baselinePath");
      if (match === "required" && match$1 !== undefined && match$2 !== undefined && match$3 !== undefined) {
        return Primitive_option.some({
          mode: "Required",
          onForbidden: Primitive_option.valFromOption(match$1),
          manifestPath: Stdlib_Option.map(Primitive_option.valFromOption(match$2), none => Nodepath.resolve(baseDir, none)),
          baselinePath: Stdlib_Option.map(Primitive_option.valFromOption(match$3), none => Nodepath.resolve(baseDir, none))
        });
      }
    });
  } else {
    return Primitive_option.some(undefined);
  }
}

function decodeStringArray(dict, key, $$default) {
  let value = dict[key];
  if (value !== undefined) {
    return Stdlib_Option.flatMap(Stdlib_JSON.Decode.array(value), values => {
      let decoded = values.map(Stdlib_JSON.Decode.string);
      if (decoded.every(Stdlib_Option.isSome)) {
        return Stdlib_Array.keepSome(decoded);
      }
    });
  } else {
    return $$default;
  }
}

function capitalizeFirst(value) {
  let first = value[0];
  if (first !== undefined) {
    return first.toUpperCase() + value.slice(1);
  } else {
    return value;
  }
}

function moduleNameFromSchemaName(name) {
  return name.split("-").flatMap(part => part.split("_")).map(capitalizeFirst).join("") + "Schema";
}

function decodeSchema(name, baseDir, projectRoot, dict, stateName) {
  let value = dict["dumpSchemaSdl"];
  let dumpSchemaSdl = value !== undefined ? Stdlib_JSON.Decode.bool(value) : false;
  let value$1 = dict["contextType"];
  let contextType = value$1 !== undefined ? Stdlib_JSON.Decode.string(value$1) : "ResGraphContext.context";
  let value$2 = dict["moduleName"];
  let moduleName = value$2 !== undefined ? Stdlib_JSON.Decode.string(value$2) : moduleNameFromSchemaName(name);
  let match = Stdlib_Option.flatMap(dict["outputFolder"], Stdlib_JSON.Decode.string);
  let match$1 = decodeStringArray(dict, "include", []);
  let match$2 = decodeStringArray(dict, "exclude", []);
  let match$3 = parseAuthorizationConfig(dict, baseDir);
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined && moduleName !== undefined && contextType !== undefined && dumpSchemaSdl !== undefined && match$3 !== undefined) {
    return {
      name: name,
      projectRoot: Nodepath.resolve(baseDir, projectRoot),
      includePaths: match$1.map(none => Nodepath.resolve(baseDir, none)),
      excludePaths: match$2.map(none => Nodepath.resolve(baseDir, none)),
      outputFolder: Nodepath.resolve(baseDir, match),
      moduleName: moduleName,
      contextType: contextType,
      dumpSchemaSdl: dumpSchemaSdl,
      authorization: Primitive_option.valFromOption(match$3),
      stateName: stateName
    };
  }
}

function parseConfig(rawConfig, baseDirOpt) {
  let baseDir = baseDirOpt !== undefined ? baseDirOpt : Process.cwd();
  let dict = Stdlib_JSON.Decode.object(rawConfig);
  if (dict === undefined) {
    return;
  }
  let rawSchemas = dict["schemas"];
  if (rawSchemas !== undefined) {
    let schemaDict = Stdlib_JSON.Decode.object(rawSchemas);
    if (schemaDict === undefined) {
      return;
    }
    let schemas = Object.entries(schemaDict).map(param => {
      let name = param[0];
      return Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(param[1]), schemaDict => {
        let value = schemaDict["projectRoot"];
        let projectRoot = value !== undefined ? Stdlib_JSON.Decode.string(value) : ".";
        return Stdlib_Option.flatMap(projectRoot, projectRoot => decodeSchema(name, baseDir, projectRoot, schemaDict, name));
      });
    });
    if (schemas.length === 0 || !schemas.every(Stdlib_Option.isSome)) {
      return;
    }
    let schemas$1 = Stdlib_Array.keepSome(schemas);
    let value = dict["defaultSchema"];
    let defaultSchema = value !== undefined ? Stdlib_JSON.Decode.string(value) : Stdlib_Option.map(schemas$1[0], schema => schema.name);
    return Stdlib_Option.flatMap(defaultSchema, defaultSchema => Stdlib_Option.map(schemas$1.find(schema => schema.name === defaultSchema), schema => {
      let authorization = schema.authorization;
      return {
        schemas: schemas$1,
        defaultSchema: defaultSchema,
        legacy: false,
        src: schema.projectRoot,
        outputFolder: schema.outputFolder,
        dumpSchemaSdl: schema.dumpSchemaSdl,
        authorization: authorization
      };
    }));
  }
  let src = Stdlib_Option.flatMap(dict["src"], Stdlib_JSON.Decode.string);
  if (src !== undefined) {
    return Stdlib_Option.map(decodeSchema("default", baseDir, src, dict, undefined), schema => {
      let newrecord = {...schema};
      newrecord.moduleName = "ResGraphSchema";
      let authorization = newrecord.authorization;
      return {
        schemas: [newrecord],
        defaultSchema: "default",
        legacy: true,
        src: newrecord.projectRoot,
        outputFolder: newrecord.outputFolder,
        dumpSchemaSdl: newrecord.dumpSchemaSdl,
        authorization: authorization
      };
    });
  }
}

function readConfigFromDir(dir) {
  let readConfigResult = parseConfig(JSON.parse(Nodefs.readFileSync(Nodepath.resolve(dir, "./resgraph.json")).toString("utf8")), dir);
  if (readConfigResult !== undefined) {
    return {
      TAG: "Ok",
      _0: readConfigResult
    };
  } else {
    return {
      TAG: "Error",
      _0: "Could not parse config, something is wrong"
    };
  }
}

function readConfigFromCwd() {
  return readConfigFromDir(Process.cwd());
}

function findSchema(config, name) {
  return config.schemas.find(schema => schema.name === name);
}

function defaultSchema(config) {
  return findSchema(config, config.defaultSchema);
}

function pathMatches(path, root) {
  if (path === root) {
    return true;
  } else {
    return path.startsWith(root + Nodepath.sep);
  }
}

function schemaForFile(config, filePath) {
  let filePath$1 = canonicalPath(filePath);
  let matching = config.schemas.filter(schema => {
    let projectRoot = canonicalPath(schema.projectRoot);
    let includePaths = schema.includePaths.map(canonicalPath);
    let excludePaths = schema.excludePaths.map(canonicalPath);
    let included = pathMatches(filePath$1, projectRoot) && (includePaths.length === 0 || includePaths.some(root => pathMatches(filePath$1, root)));
    let excluded = excludePaths.some(root => pathMatches(filePath$1, root));
    if (included) {
      return !excluded;
    } else {
      return false;
    }
  });
  if (matching.length !== 1) {
    return findSchema(config, config.defaultSchema);
  } else {
    return matching[0];
  }
}

function schemaForGraphqlFile(config, filePath) {
  let filePath$1 = canonicalPath(filePath);
  let mostSpecificSchema = {
    contents: undefined
  };
  let mostSpecificLength = {
    contents: -1
  };
  config.schemas.forEach(schema => {
    let outputFolder = canonicalPath(schema.outputFolder);
    if (pathMatches(filePath$1, outputFolder) && outputFolder.length > mostSpecificLength.contents) {
      mostSpecificSchema.contents = schema;
      mostSpecificLength.contents = outputFolder.length;
      return;
    }
  });
  return Stdlib_Option.orElse(mostSpecificSchema.contents, findSchema(config, config.defaultSchema));
}

exports.isWindows = isWindows;
exports.canonicalPath = canonicalPath;
exports.portableFilesystemIdentity = portableFilesystemIdentity;
exports.resolveRelative = resolveRelative;
exports.optionStringToArray = optionStringToArray;
exports.privateCliCallToArgs = privateCliCallToArgs;
exports.devBinLocation = devBinLocation;
exports.hasDevBin = hasDevBin;
exports.callPrivateCli = callPrivateCli;
exports.formatFindDefinitionText = formatFindDefinitionText;
exports.stringifyFindDefinitionJson = stringifyFindDefinitionJson;
exports.stringifyFindDefinitionError = stringifyFindDefinitionError;
exports.getLastBuiltFromCompilerLog = getLastBuiltFromCompilerLog;
exports.runIfCompilerDone = runIfCompilerDone;
exports.hasProjectConfig = hasProjectConfig;
exports.findCompilerRoot = findCompilerRoot;
exports.setupWatcher = setupWatcher;
exports.tempFilePrefix = tempFilePrefix;
exports.tempFileId = tempFileId;
exports.createFileInTempDir = createFileInTempDir;
exports.parseOptionalString = parseOptionalString;
exports.parseAuthorizationConfig = parseAuthorizationConfig;
exports.decodeStringArray = decodeStringArray;
exports.capitalizeFirst = capitalizeFirst;
exports.moduleNameFromSchemaName = moduleNameFromSchemaName;
exports.decodeSchema = decodeSchema;
exports.parseConfig = parseConfig;
exports.readConfigFromDir = readConfigFromDir;
exports.readConfigFromCwd = readConfigFromCwd;
exports.findSchema = findSchema;
exports.defaultSchema = defaultSchema;
exports.pathMatches = pathMatches;
exports.schemaForFile = schemaForFile;
exports.schemaForGraphqlFile = schemaForGraphqlFile;
/* isWindows Not a pure module */
